src=mac_top
tb=tb_mac_top
testname=test
verbosity=UVM_MEDIUM
.DEFAULT_GOAL := help

list: # target
	echo # rtl > list.f
	# Modificado para Linux: Busca todos los .sv en rtl
	ls ../../rtl/*.sv >> list.f
	echo # verification >> list.f
	echo ../${tb}.sv >> list.f
	
ana:
	xvlog -sv -f list.f -L uvm
elab: ana
	# Ajustado para usar el nombre de tu modulo de testbench
	xelab -debug typical --relax ${tb} -s mac_sim
sim: elab
	xsim mac_sim -runall

waves:
	xsim mac_sim.wdb -gui &

sim_gui: elab
	xsim mac_sim -runall -gui
cov: 
	xcrg -report_format html -dir xsim.covdb
sim_uvm: elab
	xsim mac_sim "UVM_TESTNAME=${testname}"

sim_uvm_gui: elab
	xsim mac_sim -gui "UVM_TESTNAME=${testname}"
help:
	@echo ""
	@echo "==== Basic Vivado Compile/Simulator makefile ======"
	@echo " Targets:"
	@echo " ana    --> Analyzes the HDL file with xvlog command"
	@echo " elab   --> Elaborates de design with xelab command"
	@echo " sim    --> Simulates the design with xsim command"
	@echo " clean  --> Clean support files"
	@echo " help   --> this help menu =)"
	@echo ""
clean:
	rm -rf xvlog* xelab* ana elab sim

	rm -f xsim.log xsim.jou xsim_*.backup.log xsim_*.backup.jou

	rm -rf xsim.covdb tr_db* webtalk*

	rm -rf xsim.dir .Xil vivado*

	rm -f work.*.wdb

	[ ! -d work ] || rm -rf work

synth:
	vivado -mode batch -source run_synth.tcl -log synth.log

open_synth:
	vivado -mode gui mac_radix4_synth.dcp &
